name: Pull code, rebuild files and restart pm2

on:
  push:
    branches: [master]

jobs:
  update:
    runs-on: ubuntu-20.04
    steps:
      - name: Rebuild app
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: |
            cd /var/www/swapmeets.xyz
            sudo git pull
            cd server
            yarn
            npx tsc
            pm2 restart server
            cd ..
            cd client
            yarn
            yarn build
            pm2 restart client
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.PRIVATE_KEY }}
