name: Pull code, rebuild files and restart pm2

on:
  push:
    branches: [master]

jobs:
  update:
    runs-on: ubuntu-20.04
    steps:
      - name: Rebuild app
        uses: garygrossgarten/github-action-ssh@release
        with:
          command: ls -la
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          privateKey: ${{ secrets.PRIVATE_KEY }}
